name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      hath_version:
        required: true
        description: version number, eg. 1.2.3
      hath_sha256:
        required: true
        description: SHA-256 checksum of zip file
      set_latest:
        type: boolean
        description: set this version as latest tag
env:
  HatH_VERSION: ${{ github.event.inputs.hath_version}}
  HatH_SHA256: ${{ github.event.inputs.hath_sha256 }}
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            HatH_VERSION=${{ env.HatH_VERSION }}
            HatH_SHA256=${{ env.HatH_SHA256 }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: ${{ format(github.event.inputs.set_latest && '{0}/hentaiathome:{1},{0}/hentaiathome:latest' || '{0}/hentaiathome:{1}', secrets.DOCKERHUB_USERNAME, env.HatH_VERSION) }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
